name: Test
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: 0.6.3
        enable-cache: true
    - name: Install Python dependencies
      run: |
        uv sync --all-extras --dev
    - name: Run tests
      env:
        MKL_NUM_THREADS: 1
      run: uv run ./scripts/test.sh
    timeout-minutes: 6
env:
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - staging-*
    - '*'
  workflow_dispatch: null
